### ISSUE TITLE
Checklist for this week (extracted some points from the milestone file)

### ISSUE THREAD

**Issue by HanyingZhang** [UBC-MDS/DSCI_532_Group_113_Overdose_R#5]
### Submission
In the README.md file of your individual milestone4 homework repo on GitHub.ubc.ca, include:
- [x] A link to team project repo on GitHub.com.
- [x] A link to your deployed app on Heroku (for e.g., https://{app-name}.herokuapp.com)
    - This MUST match the version of the app of the submitted code
- [x] A link to the reflection file

**Important**: the links you provide to your code on GitHub.com should point to a specific commit

## Things to be completed
- Overall App Deployment (15%)
    - [x] Create a branch on GitHub.com called milestone4
    - [x] Deploy your Dash app to heroku.com as described in Lecture 3 using the milestone4 branch. 
    - [x] Document the functionality of your Dash app in the README.md file in your team's GitHub.com public repo for this milestone. Also include a link to your deployed app in the README.md file.

-  Interactive Dash app in R using ggplot and ggplotly (60%)

    - [x] Build a dashboard interface for the dataset you have chosen to work with.
    - [x] Create interactive visualizations that let a user explore the dataset.
    - [x] Implement the features you outlined in your proposal, paying close attention to usability.
    - [x] Keep your usage scenario (from your proposal) in mind when designing your interface. Make sure that your app's interface and functionality would allow a user to answer your proposed questions.
    - [x] Your interface should be as self-documenting as possible, with appropriate labels for panes and widgets, a legend documenting the meaning of visual encodings, and a meaningful title for the app.

- [x] -  Reflection (10%)
